apiVersion: managed.cloudflare.upbound.io/v1alpha1
kind: Headers
metadata:
  annotations:
    meta.upbound.io/example-id: managed/v1alpha1/headers
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    managedRequestHeaders:
    - enabled: true
      id: add_true_client_ip_headers
    managedResponseHeaders:
    - enabled: true
      id: remove_x-powered-by_header
    zoneId: 0da42c8d2132a9ddaf714f9e7c920711
