//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Headers) DeepCopyInto(out *Headers) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Headers.
func (in *Headers) DeepCopy() *Headers {
	if in == nil {
		return nil
	}
	out := new(Headers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Headers) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersInitParameters) DeepCopyInto(out *HeadersInitParameters) {
	*out = *in
	if in.ManagedRequestHeaders != nil {
		in, out := &in.ManagedRequestHeaders, &out.ManagedRequestHeaders
		*out = make([]ManagedRequestHeadersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedResponseHeaders != nil {
		in, out := &in.ManagedResponseHeaders, &out.ManagedResponseHeaders
		*out = make([]ManagedResponseHeadersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersInitParameters.
func (in *HeadersInitParameters) DeepCopy() *HeadersInitParameters {
	if in == nil {
		return nil
	}
	out := new(HeadersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersList) DeepCopyInto(out *HeadersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Headers, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersList.
func (in *HeadersList) DeepCopy() *HeadersList {
	if in == nil {
		return nil
	}
	out := new(HeadersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeadersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersObservation) DeepCopyInto(out *HeadersObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ManagedRequestHeaders != nil {
		in, out := &in.ManagedRequestHeaders, &out.ManagedRequestHeaders
		*out = make([]ManagedRequestHeadersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedResponseHeaders != nil {
		in, out := &in.ManagedResponseHeaders, &out.ManagedResponseHeaders
		*out = make([]ManagedResponseHeadersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersObservation.
func (in *HeadersObservation) DeepCopy() *HeadersObservation {
	if in == nil {
		return nil
	}
	out := new(HeadersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersParameters) DeepCopyInto(out *HeadersParameters) {
	*out = *in
	if in.ManagedRequestHeaders != nil {
		in, out := &in.ManagedRequestHeaders, &out.ManagedRequestHeaders
		*out = make([]ManagedRequestHeadersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedResponseHeaders != nil {
		in, out := &in.ManagedResponseHeaders, &out.ManagedResponseHeaders
		*out = make([]ManagedResponseHeadersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersParameters.
func (in *HeadersParameters) DeepCopy() *HeadersParameters {
	if in == nil {
		return nil
	}
	out := new(HeadersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersSpec) DeepCopyInto(out *HeadersSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersSpec.
func (in *HeadersSpec) DeepCopy() *HeadersSpec {
	if in == nil {
		return nil
	}
	out := new(HeadersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersStatus) DeepCopyInto(out *HeadersStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersStatus.
func (in *HeadersStatus) DeepCopy() *HeadersStatus {
	if in == nil {
		return nil
	}
	out := new(HeadersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRequestHeadersInitParameters) DeepCopyInto(out *ManagedRequestHeadersInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRequestHeadersInitParameters.
func (in *ManagedRequestHeadersInitParameters) DeepCopy() *ManagedRequestHeadersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedRequestHeadersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRequestHeadersObservation) DeepCopyInto(out *ManagedRequestHeadersObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRequestHeadersObservation.
func (in *ManagedRequestHeadersObservation) DeepCopy() *ManagedRequestHeadersObservation {
	if in == nil {
		return nil
	}
	out := new(ManagedRequestHeadersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRequestHeadersParameters) DeepCopyInto(out *ManagedRequestHeadersParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRequestHeadersParameters.
func (in *ManagedRequestHeadersParameters) DeepCopy() *ManagedRequestHeadersParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedRequestHeadersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResponseHeadersInitParameters) DeepCopyInto(out *ManagedResponseHeadersInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResponseHeadersInitParameters.
func (in *ManagedResponseHeadersInitParameters) DeepCopy() *ManagedResponseHeadersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedResponseHeadersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResponseHeadersObservation) DeepCopyInto(out *ManagedResponseHeadersObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResponseHeadersObservation.
func (in *ManagedResponseHeadersObservation) DeepCopy() *ManagedResponseHeadersObservation {
	if in == nil {
		return nil
	}
	out := new(ManagedResponseHeadersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResponseHeadersParameters) DeepCopyInto(out *ManagedResponseHeadersParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResponseHeadersParameters.
func (in *ManagedResponseHeadersParameters) DeepCopy() *ManagedResponseHeadersParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedResponseHeadersParameters)
	in.DeepCopyInto(out)
	return out
}
