apiVersion: user.cloudflare.upbound.io/v1alpha1
kind: AgentBlockingRule
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/agentblockingrule
  labels:
    testing.upbound.io/example-name: example_1
  name: example-1
spec:
  forProvider:
    configuration:
    - target: ua
      value: Chrome
    description: My description 1
    mode: js_challenge
    paused: false
    zoneId: 0da42c8d2132a9ddaf714f9e7c920711
